# Data Processing for INX Future Inc Employee Performance Analysis

This notebook focuses on data loading, inspection, cleaning, and preprocessing
required for employee performance analysis at INX Future Inc. The processed
dataset generated from this notebook will be used for exploratory analysis
and machine learning model development.

## Import Required Libraries

Pandas is used for data manipulation.

NumPy is used for numerical operations

In [ ]:
import pandas as pd
import numpy as np

## Load Raw Dataset

The dataset is loaded from the raw data directory to ensure immutability of original data.

In [ ]:
# Load the raw dataset
df = pd.read_excel(r"C:\Users\madha\Desktop\Employee Performance Analysis\data\raw\INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls")
# Display first 5 rows
df.head()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,...,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,...,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,...,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,...,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,...,4,10,1,3,2,2,2,2,No,3

## Basic Data Inspection

Dataset contains 1200 employee records

Includes numerical and categorical features

No missing values observed (important insight!)

In [ ]:
# Shape of the dataset
df.shape

(1200, 28)

In [ ]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EmpNumber                     1200 non-null   object
 1   Age                           1200 non-null   int64
 2   Gender                        1200 non-null   object
 3   EducationBackground           1200 non-null   object
 4   MaritalStatus                 1200 non-null   object
 5   EmpDepartment                 1200 non-null   object
 6   EmpJobRole                    1200 non-null   object
 7   BusinessTravelFrequency       1200 non-null   object
 8   DistanceFromHome              1200 non-null   int64
 9   EmpEducationLevel             1200 non-null   int64
 10  EmpEnvironmentSatisfaction    1200 non-null   int64
 11  EmpHourlyRate                 1200 non-null   int64
 12  EmpJobInvolvement             1200 non-null   int64
 13  EmpJobLevel                   1200 non-null   int64
 14  EmpJobSatisfaction            1200 non-null   int64
 15  NumCompaniesWorked            1200 non-null   int64
 16  OverTime                      1200 non-null   object
 17  EmpLastSalaryHikePercent      1200 non-null   int64
 18  EmpRelationshipSatisfaction   1200 non-null   int64
 19  TotalWorkExperienceInYears    1200 non-null   int64
 20  TrainingTimesLastYear         1200 non-null   int64
 21  EmpWorkLifeBalance            1200 non-null   int64
 22  ExperienceYearsAtThisCompany  1200 non-null   int64
 23  ExperienceYearsInCurrentRole  1200 non-null   int64
 24  YearsSinceLastPromotion       1200 non-null   int64
 25  YearsWithCurrManager          1200 non-null   int64
 26  Attrition                     1200 non-null   object
 27  PerformanceRating             1200 non-null   int64
dtypes: int64(19), object(9)
memory usage: 262.6+ KB

In [ ]:
# Statistical summary
df.describe()

,Age,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,PerformanceRating
count,1200.000000,1200.000000,1200.00000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,36.918333,9.165833,2.89250,2.715833,65.981667,2.731667,2.067500,2.732500,2.665000,15.222500,2.725000,11.330000,2.785833,2.744167,7.077500,4.291667,2.194167,4.105000,2.948333
std,9.087289,8.176636,1.04412,1.090599,20.211302,0.707164,1.107836,1.100888,2.469384,3.625918,1.075642,7.797228,1.263446,0.699374,6.236899,3.613744,3.221560,3.541576,0.518866
min,18.000000,1.000000,1.00000,1.000000,30.000000,1.000000,1.000000,1.000000,0.000000,11.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,30.000000,2.000000,2.00000,2.000000,48.000000,2.000000,1.000000,2.000000,1.000000,12.000000,2.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000,3.000000
50%,36.000000,7.000000,3.00000,3.000000,66.000000,3.000000,2.000000,3.000000,2.000000,14.000000,3.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000,3.000000
75%,43.000000,14.000000,4.00000,4.000000,83.000000,3.000000,3.000000,4.000000,4.000000,18.000000,4.000000,15.000000,3.000000,3.000000,10.000000,7.000000,3.000000,7.000000,3.000000
max,60.000000,29.000000,5.00000,4.000000,100.000000,4.000000,5.000000,4.000000,9.000000,25.000000,4.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000,4.000000

## Missing Value Check

The dataset does not contain missing values, eliminating the need for imputation.

In [ ]:
df.isnull().sum()

EmpNumber                       0
Age                             0
Gender                          0
EducationBackground             0
MaritalStatus                   0
EmpDepartment                   0
EmpJobRole                      0
BusinessTravelFrequency         0
DistanceFromHome                0
EmpEducationLevel               0
EmpEnvironmentSatisfaction      0
EmpHourlyRate                   0
EmpJobInvolvement               0
EmpJobLevel                     0
EmpJobSatisfaction              0
NumCompaniesWorked              0
OverTime                        0
EmpLastSalaryHikePercent        0
EmpRelationshipSatisfaction     0
TotalWorkExperienceInYears      0
TrainingTimesLastYear           0
EmpWorkLifeBalance              0
ExperienceYearsAtThisCompany    0
ExperienceYearsInCurrentRole    0
YearsSinceLastPromotion         0
YearsWithCurrManager            0
Attrition                       0
PerformanceRating               0
dtype: int64

## Drop Unnecessary Columns

In [ ]:
# Employee Number is a unique identifier and not useful for prediction
df.drop(columns=['EmpNumber'], inplace=True)

In [ ]:
# Feature Engineering - HR meaningful features

df["ExperienceRatio"] = (
    df["ExperienceYearsInCurrentRole"] /
    (df["TotalWorkExperienceInYears"] + 1)
)

df["PromotionGap"] = (
    df["YearsSinceLastPromotion"] /
    (df["ExperienceYearsAtThisCompany"] + 1)
)

## Encode Categorical Variables

In [ ]:
# Identify categorical columns
categorical_cols = df.select_dtypes(include='object').columns
categorical_cols

# Apply Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

## Define Features and Target

In [ ]:
X = df.drop(columns=['PerformanceRating'])
y = df['PerformanceRating']

## Save Processed Dataset

In [ ]:
# Save processed data
df.to_csv(r"C:\Users\madha\Desktop\Employee Performance Analysis/data/processed/employee_performance_processed.csv", index=False)

#The cleaned dataset is stored separately to maintain reproducibility.